### PR TITLE
Add content negotiation and create JSON-LD format for feature responses

### LINKED ISSUE #298: Output individual NLDI feature as json-ld representation.
Based on the outcome of #280 allow f=jsonld or the appropriate content type header to trigger the jsonld media type response. This would include the mainstem the feature is on and the `@id` of the feature is to be the existing `url` attribute of the feature.

### LINKED ISSUE #303: Separate comid and featureSource/featureID endpoints
Right now the `/linked-data/{featureSource}/{featureID}` also catches the `/linked-data/comid/{comid}` requests. With the new content negotiation, the source/ID endpoint is expected to return a `Feature` object. A new comid endpoint mapping should be created that returns a `Comid` object instead.

### PR DESCRIPTION
**Pull request by EthanGrahn**
Before making a pull request
----------------------------

- [x] Make pull request title clear and descriptive
- [x] Link(s) to issue describing bug fixed or need for change
- [x] Make sure all tests run
- [x] Update the changelog appropriately

Description
---------------------------
Enabled WebMVC for all controllers and enabled content negotiation. The endpoints now respect `Accept` headers and the format parameter (e.g. `?f=json`), favoring the parameter. Each endpoints was updated to accept the appropriate combination of JSON, GeoJSON, or JSON-LD.

To support the content negotiation, I have added several message converters to handle converting reponse object to the necessary formats. Message converters may be added or edited to fit future content types.

The primary endpoint with a new format is `/linked-data/{featureSource}/{featureID}?f=jsonld` which returns valid JSON-LD. Closes #298 

The comid endpoint has been separated from the feature endpoint to allow separate conversion as necessary. Closes #303 

The feature endpoint supports utilizing the new shape column, but will fallback to using the previous location column. This starts to cover #248 but several other queries need to be updated before it can be closed. 

Reviewers, use [this link](https://github.com/internetofwater/nldi-services/pull/304/files/7bf63e2a7edfec23058e0c1eb12ff11db4e8432c) to view code changes without linting changes.

After making a pull request
---------------------------
- [x] If appropriate, put the link to the PR in the JIRA ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by EthanGrahn** [comment]
And it won't need `"@id": "hyf:linearElement"`?

**Comment by ksonda** [comment]
That's not strictly necessary since hyf is in the context,

I would say it either makes more sense to have aliases for both mainstem and reachcode which are the same, or do neither, and have hyf:linearElement in the context as above.

**Comment by EthanGrahn** [comment]
In that case, I'll switch it to not having an alias and using `hyf:linearElement` for both instead.

**Review by hillc-usgs — APPROVED** [review]
LGTM

**Pull request merged**
